### PR TITLE
Make config a bit more formal

### PR DESCRIPTION
**Pull request by foolswood**
What do you like/dislike about this as a shape?

### CODE REVIEW

**Comment by Lantero** [comment]
We could summarize the points we want to fix/improve and then come up with something that addresses them, so like:
- Better user experience if any config value is missing.
- Type validation with callbacks or something like that.
- Accept .yaml/.json config files.
- Sensible defaults whenever possible.
In general, I like your idea of having named tuples as our model for handling the config values.

As for the configuration requirement goes, only the session config is strictly required (host, port, username and password), as everything else can be set as part of the class constructor or being set through instance attributes, so we can make those a static check/pre-requisite. Some stuff like SSH/WinRM credentials are only needed if you want to run those commands, so we probably want a dynamic check for those (I'm doing sort of a similar thing in the code of those functions, but that could be abstracted out to be a config responsibility). So something like this would be neat:
```
from vcdriver.config import requires

def foo():
    with requires('vm_ssh_username', 'vm_ssh_password'):  # Check for env vars, .yaml and .json and throw some nice exception if missing
        print('foo')   
```

**Comment by Lantero** [comment]
We could also use the same singleton-in-a-module pattern I used to handle the session, just brainstorming here a bit :slightly_smiling_face:

**Comment by foolswood** [comment]
My feeling on that is that having a default config is good, but the library shouldn't limit you to talking to one vsphere at a time, which enforcing that it is a singleton would do.

**Comment by foolswood** [comment]
I've been batted away from this, I'm intending to come back to the deploying stuff at some point, but I don't know exactly when and don't want to leave this hanging.

**Comment by Lantero** [comment]
The config is something that definitely needs to be improved and I appreciate your interest and the second pair of eyes on it. I have been thinking about it a bit more than the brainshitstorming of my previous comments, and I think the two main problems we should address are:
- Better errors if config is missing
- The fact that importing the config is not lazy, atm you have to set the environment before the imports

Furthermore, I would like to allow configuration injection at different levels:
1. Let the user pass parameters to the functions, if you don't mind about having more lines of code and don't want to fiddle with env vars or config files.
2. Look at the environment as a fallback for those missing parameters.
3. Optionally, let the user load config from some sort of `.json`, `.yml` or `.ini` config file.

If I can find a time gap before you do I'll try to move this forward!

**Pull request closed without merging**
